version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
    ignore:
    # The way we are using 2 different versions of the mshv crates seems to break dependabot
      - dependency-name: "mshv-ioctls"
        versions: [ ">=0.2.1" ]
      - dependency-name: "mshv-bindings"
        versions: [ ">=0.2.1" ]
    open-pull-requests-limit: 20
  - package-ecosystem: "cargo"
    directory: "/src/tests/rust_guests/dummyguest"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
      - "area/guest"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/src/tests/rust_guests/simpleguest"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
      - "area/guest"
    open-pull-requests-limit: 5
  - package-ecosystem: "cargo"
    directory: "/src/tests/rust_guests/witguest"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
      - "area/guest"
    open-pull-requests-limit: 5
