[default]
extend-ignore-identifiers-re = ["Fo", "edn", "ue"]

[files]
extend-exclude = ["**/*.patch", "src/hyperlight_guest_bin/third_party/**/*", "NOTICE.txt"]

[default.extend-words]
# typ is used for field name as type is a reserved keyword
typ="typ"
