[package]
name = "hyperlight-guest"
links = "c"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = """
Library to build guest applications for hyperlight.
"""

[features]
default = ["libc", "printf", "alloca"]
libc = [] # compile musl libc
printf = [] # compile printf
alloca = [] # compile alloca wrapper

[dependencies]
anyhow = { version = "1.0.94", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
buddy_system_allocator = "0.11.0"
hyperlight-common = { workspace = true }
spin = "0.9.8"
log = { version = "0.4", default-features = false }

[build-dependencies]
cc = "1.2"
cfg-if = "1.0"
glob = "0.3.1"