[package]
name = "hyperlight-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = """
A lightweight Virtual Machine Manager that can be hosted in an application to safely
run untrusted or code within a VM partition with very low latency and overhead.
"""

[lib]
# https://docs.rust-embedded.org/book/interoperability/rust-with-c.html
name = "hyperlight_host"
bench = false # see https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options

[lints]
workspace = true

[dependencies]
goblin = { version = "0.9" }
rand = { version = "0.9" }
cfg-if = { version = "1.0.0" }
libc = { version = "0.2.170" }
paste = "1.0"
flatbuffers = "25.2.10"
page_size = "0.6.0"
termcolor = "1.2.0"
bitflags = "2.8.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.25"
once_cell = { version = "1.20.3" }
tracing = { version = "0.1.41", features = ["log"] }
tracing-log = "0.2.0"
tracing-core = "0.1.33"
hyperlight-common = { workspace = true, default-features = true }
vmm-sys-util = "0.12.1"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.14"
thiserror = "2.0.11"
prometheus = "0.13.3"
strum = { version = "0.27", features = ["derive"] }
tempfile = { version = "3.17", optional = true }
serde_yaml = "0.9"
anyhow = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_JobObjects",
    "Win32_Security",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Hypervisor",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_JobObjects",
    "Win32_System_SystemServices",
] }
windows-sys = { version = "0.59", features = ["Win32"] }
windows-result = "0.3"
rust-embed = { version = "8.3.0", features = ["debug-embed", "include-exclude", "interpolate-folder-path"] }
sha256 = "1.4.0"
windows-version = "0.1"

[target.'cfg(unix)'.dependencies]
gdbstub = { version = "0.7.3", optional = true }
gdbstub_arch = { version = "0.3.1", optional = true }
seccompiler = { version = "0.4.0", optional = true }
kvm-bindings = { version = "0.11", features = ["fam-wrappers"], optional = true }
kvm-ioctls = { version = "0.20", optional = true }
mshv-bindings2 = { package="mshv-bindings", version = "=0.2.1", optional = true }
mshv-ioctls2 = { package="mshv-ioctls",  version = "=0.2.1", optional = true}
mshv-bindings3 = { package="mshv-bindings", version = "=0.3.2", optional = true }
mshv-ioctls3 = { package="mshv-ioctls",  version = "=0.3.2", optional = true}

[dev-dependencies]
uuid = { version = "1.15.1", features = ["v4"] }
signal-hook-registry = "1.4.1"
envy = { version = "0.4.2" }
serde = "1.0"
proptest = "1.6.0"
tempfile = "3.17.1"
crossbeam-queue = "0.3.12"
tracing-serde = "0.2.0"
serial_test = "3.1.1"
hyperlight-testing = { workspace = true }
env_logger = "0.11.6"
tracing-forest = { version = "0.1.6", features = ["uuid", "chrono", "smallvec", "serde", "env-filter"] }
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["std", "env-filter"]}
tracing-opentelemetry = "0.29.0"
opentelemetry = "0.28"
opentelemetry-otlp = { version = "0.28", features = ["default", "grpc-tonic"] }
opentelemetry-semantic-conventions = "0.28"
opentelemetry_sdk = { version = "0.28", features = ["rt-tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
criterion = "0.5.1"
tracing-chrome = "0.7.2"

[target.'cfg(windows)'.dev-dependencies]
windows = { version = "0.59", features = [
    "Win32_System_Diagnostics_ToolHelp",
] }

[target.'cfg(unix)'.dev-dependencies]
proc-maps = "0.4.0"

[build-dependencies]
anyhow = { version = "1.0.96" }
cfg_aliases = "0.2.1"
built = { version = "0.7.7", features = ["chrono", "git2"] }

[features]
default = ["kvm", "mshv2", "seccomp"]
seccomp = ["dep:seccompiler"]
function_call_metrics = []
executable_heap = []
# This feature enables printing of debug information to stdout in debug builds
print_debug = []
crashdump = ["dep:tempfile"] # Dumps the VM state to a file on unexpected errors or crashes. The path of the file will be printed on stdout and logged. This feature can only be used in debug builds.
kvm = ["dep:kvm-bindings", "dep:kvm-ioctls"]
mshv2 = ["dep:mshv-bindings2", "dep:mshv-ioctls2"]
mshv3 = ["dep:mshv-bindings3", "dep:mshv-ioctls3"]
inprocess = []
# This enables easy debug in the guest
gdb = ["dep:gdbstub", "dep:gdbstub_arch"]

[[bench]]
name = "benchmarks"
harness = false
