# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Rust Tests and Lints

# See README.md in this directory for more information about workflow_call
on:
  workflow_call:
    inputs:
      docs_only:
        description: Skip building if docs only
        required: false
        type: string
        default: "false"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: ${{ inputs.docs_only == 'false' }}
    strategy:
      fail-fast: true
      matrix:
        hypervisor: [hyperv, mshv, kvm] # hyperv is windows, mshv and kvm are linux
        cpu: [amd, intel]
        config: [debug, release]

    runs-on: ${{ fromJson(format('["self-hosted", "{0}", "X64", "1ES.Pool=hld-{1}-{2}"]', matrix.hypervisor == 'hyperv' && 'Windows' || 'Linux', matrix.hypervisor == 'hyperv' && 'win2022' || matrix.hypervisor, matrix.cpu)) }} 
    steps:
      - uses: actions/checkout@v4

      - uses: hyperlight-dev/ci-setup-workflow@v1.1.0
        with:
          rust-toolchain: "nightly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: fmt
        run: just fmt-check

      - name: clippy
        run: just clippy ${{ matrix.config }}

      - name: Ensure up-to-date Cargo.lock
        run: |
          cargo fetch --locked
          cargo fetch --manifest-path src/tests/rust_guests/simpleguest/Cargo.toml --locked
          cargo fetch --manifest-path src/tests/rust_guests/callbackguest/Cargo.toml --locked

      - name: Get gh action service name
        if: ${{ (runner.os == 'Windows' )}}
        run: (Get-Service actions.runner.*) | Foreach { $_.Name, $_.UserName, $_.ServiceType }
        shell: pwsh

      - name: Build and move Rust guests
        run: just build-and-move-rust-guests

      - name: Build c guests
        run: just build-and-move-c-guests

      - name: Build
        run: just build-rust ${{ matrix.config }}

      - name: Verify MSRV
        run: ./dev/verify-msrv.sh hyperlight-host hyperlight-guest hyperlight-common
        shell: bash

      - name: Run Rust tests
        env:
          CARGO_TERM_COLOR: always
        run: |
          # with default features
          just test-rust ${{ matrix.config }}

          # with only one driver enabled (driver mshv/kvm feature is ignored on windows) + seccomp + inprocess
          just test-rust ${{ matrix.config }} inprocess,seccomp,${{ matrix.hypervisor == 'mshv' && 'mshv' || 'kvm' }} 

          # make sure certain cargo features compile
          cargo check -p hyperlight-host --features crashdump
          cargo check -p hyperlight-host --features print_debug

          # without any driver (shouldn't compile)
          just test-rust-feature-compilation-fail ${{ matrix.config }}

        # One of the examples is flaky on Windows GH runners, so this allows us to disable it for now
      - name: Run Rust examples - windows
        if: ${{ (runner.os == 'Windows') }}
        env:
          CARGO_TERM_COLOR: always
          RUST_LOG: debug
        run: just run-rust-examples ${{ matrix.config }}

      - name: Run Rust examples - linux
        if: ${{ (runner.os != 'Windows') }}
        env:
          CARGO_TERM_COLOR: always
          RUST_LOG: debug
        run: just run-rust-examples-linux ${{ matrix.config }}

      ### Benchmarks ###
      - name: Install github-cli (Linux mariner)
        if: runner.os == 'Linux' && matrix.hypervisor == 'mshv'
        run: sudo dnf install gh -y

      - name: Install github-cli (Linux ubuntu)
        if: runner.os == 'Linux' && matrix.hypervisor == 'kvm'
        run: sudo apt install gh -y

      - name: Download benchmarks from "latest"
        run: just bench-download ${{ runner.os }} ${{ matrix.hypervisor }} ${{ matrix.cpu}} dev-latest # compare to prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        if: ${{ matrix.config == 'release' }}

      - name: Run benchmarks
        run: |
          just bench-ci main ${{ matrix.config }}
        if: ${{ matrix.config == 'release' }}
